// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InjectedMessageRole } from "./InjectedMessageRole";

export type InjectedMessage = { role: InjectedMessageRole,
/**
 * Plain-text message content. Use `thread/inject_items` when you need raw
 * Responses API item control or non-text content.
 */
text: string, };
