// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Personality } from "../Personality";
import type { ReasoningSummary } from "../ReasoningSummary";
import type { ServiceTier } from "../ServiceTier";
import type { WindowsSandboxLevel } from "../WindowsSandboxLevel";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { PermissionProfile } from "./PermissionProfile";
import type { SandboxPolicy } from "./SandboxPolicy";

export type ThreadUpdateParams = {threadId: string, cwd?: string | null, approvalPolicy?: AskForApproval | null, approvalsReviewer?: ApprovalsReviewer | null, sandboxPolicy?: SandboxPolicy | null, permissionProfile?: PermissionProfile | null, windowsSandboxLevel?: WindowsSandboxLevel | null, model?: string | null, effort?: "none" | "minimal" | "low" | "medium" | "high" | "xhigh" | null, summary?: ReasoningSummary | null, serviceTier?: ServiceTier | null | null, personality?: Personality | null, baseInstructions?: string | null, developerInstructions?: string | null};
