// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Personality } from "../Personality";
import type { ServiceTier } from "../ServiceTier";
import type { JsonValue } from "../serde_json/JsonValue";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { InjectedMessage } from "./InjectedMessage";
import type { SandboxMode } from "./SandboxMode";

export type ThreadImportTranscriptParams = {
/**
 * Optional source thread used to inherit defaults such as cwd and stored
 * metadata. The imported transcript still creates a fresh thread id.
 */
sourceThreadId?: string | null, model?: string | null, modelProvider?: string | null, serviceTier?: ServiceTier | null | null, cwd?: string | null, approvalPolicy?: AskForApproval | null, approvalsReviewer?: ApprovalsReviewer | null, sandbox?: SandboxMode | null, config?: { [key in string]?: JsonValue } | null, baseInstructions?: string | null, developerInstructions?: string | null, personality?: Personality | null, ephemeral?: boolean, persistExtendedHistory: boolean, messages: Array<InjectedMessage>, };
