// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InjectedMessage } from "./InjectedMessage";

export type ThreadInjectMessagesParams = { threadId: string,
/**
 * Typed text messages to append to the thread's model-visible history.
 *
 * Assistant messages are stored as `output_text`; user and developer
 * messages use `input_text`.
 */
messages: Array<InjectedMessage>, };
